version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
#    depends_on:
#      - db
#    environment:
#      DB_HOST: db
#      DB_PORT: 5432
#      DB_NAME: mydatabase
#      DB_USER: myuser
#      DB_PASSWORD: mypassword
#
#  db:
#    image: postgres:13
#    restart: always
#    environment:
#      POSTGRES_DB: mydatabase
#      POSTGRES_USER: myuser
#      POSTGRES_PASSWORD: mypassword
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
#    command: postgres -c max_connections=200
#
#volumes:
#  postgres-data:
#    driver: local